---
title: "Data Visualizations with ggplot"
author: "J.Blondeau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This week is all about making plots and graphs in ggplot2.  The only datasets you need are in the /data directory.

1) sttstj_fish_biomass
2) taxonomic


Inspect the sttstj_fish_biomass dataset.  It is 5 years of biomass (kg/177m2) data for 9 fish species inside the VI national park (prot = 1) and outside the national park (prot = 0). 

In this instance, anytime you need to group by and summarize, you can just take the mean of biomass and SE.  This is not always appropriate, but for this case the exercises are for plotting and graphing.

1. Create a line graph of biomass over time for Red hind ("EPI GUTT") inside the national park.  The title of the graph should use Scientific name.

2. Create a point and line graph of biomass over time for Yellowtail Snapper ("OCY CHRY") outside the national park. The title of the graph should use **italicized** Scientific name.

3. Create a bar graph of biomass over time for all parrotfish grouped by protected_status.  Edit the the axis and legend titles to be more insightful.
    - biomass units
    - Scientific name instead of SPECIES_CD
    - 0 = Open, 1 = VI National Park
    
4. Create a bar graph of trophic-level mean biomass inside and outside VI national park. Hint: You will pool all 5 years 

5. Create a point and line plot of 'grouper' biomass (+- SE) over time; inside and outside park plots will be on the same graph. Hint: SE = square root of var.